baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Yuqoi"

[outputs]
home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
    
[params]
description = "Welcome on my own portfolio :)"
keywords = ["blog", "projects", "Yuqoi", "Aleksander Radłowski", "software development", "programming"]
author = "Yuqoi"