baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Yuqoi"

[outputs]
home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
    